/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.HocSinDao;
import dao.PhuHuynhDao;
import helpers.DataValidator;
import helpers.MessageQLHSDialog;
import model.HocSinh;
import model.Phuhuynh;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class PhuHuynh extends javax.swing.JPanel {
    
    private MainForm parentForm;
    private DefaultTableModel tblModel;
    /**
     * Creates new form PhuHuynh
     */
      public PhuHuynh() {
        initComponents();
        
        initTable();
        
        loadDataTable();
    }
     
     private void initTable() {
        tblModel = new  DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Học Sinh","Tên cha","Số điện thoại","Nghề nghiệp","Tên mẹ","Số điện thoại","Nghề nghiệp"});
        tblPHHS.setModel(tblModel);
    }
    
    private void loadDataTable(){
        try{
            PhuHuynhDao dao = new PhuHuynhDao();
            List<Phuhuynh> list = dao.findAll();
            tblModel.setRowCount(0);
            for (Phuhuynh it : list){
                tblModel.addRow(new Object[]{
                        it.getMaHS(), it.getTencha(), it.getSdtcha(), it.getNncha(), it.getTenme(), it.getSdtme(), it.getNnme()
                        });
            }tblModel.fireTableDataChanged();   
        }catch(Exception e){
            e.printStackTrace();
            MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        PHHSPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaHS = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLop = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTencha = new javax.swing.JTextField();
        txtSDTcha = new javax.swing.JTextField();
        txtNNcha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSDTme = new javax.swing.JTextField();
        txtNNme = new javax.swing.JTextField();
        txtTenme = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPHHS = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtmaHSsearch = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jSeparator1);

        jLabel3.setText("Mã học sinh");

        jLabel4.setText("Mã học sinh");

        jLabel5.setText("Họ và tên ");

        txtMaHS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaHSFocusLost(evt);
            }
        });
        txtMaHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHSActionPerformed(evt);
            }
        });

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        jLabel16.setText("Lớp");

        txtLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLopActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên cha");

        jLabel6.setText("SDT");

        jLabel7.setText("Nghề nghiệp");

        txtNNcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNNchaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tên mẹ");

        jLabel9.setText("SDT");

        jLabel10.setText("Nghề nghiệp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTen)
                            .addComponent(txtLop)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSDTcha, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel9))
                            .addComponent(txtMaHS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTencha, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNNcha, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(50, 50, 50)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtSDTme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNNme, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTencha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTenme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSDTcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSDTme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNNcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(txtNNme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quản lý thông tin phụ huynh học sinh");

        tblPHHS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPHHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPHHSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPHHS);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-16.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-icon-16.png"))); // NOI18N
        btnNew.setText("Tạo mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save-icon.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PHHSPanelLayout = new javax.swing.GroupLayout(PHHSPanel);
        PHHSPanel.setLayout(PHHSPanelLayout);
        PHHSPanelLayout.setHorizontalGroup(
            PHHSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHHSPanelLayout.createSequentialGroup()
                .addGroup(PHHSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHHSPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PHHSPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(53, 53, 53)
                        .addComponent(txtmaHSsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnSearch))
                    .addGroup(PHHSPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(PHHSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 30, Short.MAX_VALUE))
            .addComponent(jSeparator3)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PHHSPanelLayout.setVerticalGroup(
            PHHSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHHSPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PHHSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHHSPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PHHSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addGap(20, 20, 20)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete))
                    .addGroup(PHHSPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtmaHSsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(PHHSPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaHSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaHSFocusLost
        try {
            HocSinDao dao = new HocSinDao();
            HocSinh hs = dao.findmaHS(txtMaHS.getText());
            if (hs != null) {
                txtTen.setText(hs.getTenHS());
                txtLop.setText(hs.getLop());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtMaHSFocusLost

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLopActionPerformed

    private void txtNNchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNNchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNNchaActionPerformed

    private void txtMaHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHSActionPerformed

    private void tblPHHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPHHSMouseClicked
        try { 
            int row = tblPHHS.getSelectedRow();
            if(row>=0){ 
                String id = (String) tblPHHS.getValueAt(row, 0);
                HocSinDao dao = new HocSinDao();
                HocSinh hs = dao.findmaHS(id);
                PhuHuynhDao dao1 = new PhuHuynhDao();
                Phuhuynh ph = dao1.findmaHS(id);
                if(hs!=null){
                    txtMaHS.setText(ph.getMaHS());
                    txtTen.setText(hs.getLop());
                    txtLop.setText(hs.getTenHS());
                    txtTencha.setText(ph.getTencha());
                    txtSDTcha.setText(ph.getSdtcha());
                    txtNNcha.setText(ph.getNncha());
                    txtTenme.setText(ph.getTenme());
                    txtSDTme.setText(ph.getSdtme());
                    txtNNme.setText(ph.getNnme());
                }
            }
        }catch(Exception e){ 
            e.printStackTrace();
            MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblPHHSMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
            try{
            HocSinDao dao = new HocSinDao();
            HocSinh hs = dao.findmaHS(txtmaHSsearch.getText());
            PhuHuynhDao dao1 = new PhuHuynhDao();
            Phuhuynh ph = dao1.findmaHS(txtmaHSsearch.getText());
            
            if(ph!=null){
                txtMaHS.setText(ph.getMaHS());
                txtTen.setText(hs.getTenHS());
                txtLop.setText(hs.getLop());
                txtTencha.setText(ph.getTencha());
                txtSDTcha.setText(ph.getSdtcha());
                txtNNcha.setText(ph.getNncha());
                txtTenme.setText(ph.getTenme());
                txtSDTme.setText(ph.getSdtme());
                txtNNme.setText(ph.getNnme());
               
                txtMaHSFocusLost(null);
            }else{
                MessageQLHSDialog.showMessageDialog(parentForm, "Không tìm thấy học sinh cần tìm", "Thông báo");
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(),  "Lỗi");
        }                     
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtmaHSsearch.setText("");
        txtMaHS.setText("");
        txtTen.setText("");
        txtLop.setText("");
        txtTencha.setText("");
        txtSDTcha.setText("");
        txtNNcha.setText("");
        txtTenme.setText("");
        txtSDTme.setText("");
        txtNNme.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    StringBuilder sb = new StringBuilder();
    DataValidator.validateEmpty(txtMaHS, sb, "Mã học sinh cần nhập");
    if (sb.length() > 0) {
        MessageQLHSDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
        return;
    }
    try {
        Phuhuynh ph = new Phuhuynh();
        ph.setMaHS(txtMaHS.getText());
        ph.setTencha(txtTencha.getText());
        ph.setSdtcha(txtSDTcha.getText());
        ph.setNncha(txtNNcha.getText());
        ph.setTenme(txtTenme.getText());
        ph.setSdtme(txtSDTme.getText());
        ph.setNnme(txtNNme.getText());
        
        PhuHuynhDao dao = new PhuHuynhDao();

        if (dao.findmaHS(txtMaHS.getText()) != null) {
            if (MessageQLHSDialog.showConfirmDialog(parentForm, "Bạn có muốn lưu thông tin phụ huynh không", "Hỏi") == JOptionPane.YES_OPTION) {
                return;
            }
            if (dao.update(ph)) {
                MessageQLHSDialog.showMessageDialog(parentForm, "Thông tin phụ huynh đã được lưu", "Thông báo");
            } else {
                MessageQLHSDialog.showMessageDialog(parentForm, "Thông tin phụ huynh không được lưu do lỗi", "Cảnh báo");
            }
        } else {
            if (dao.insert(ph)) {
                MessageQLHSDialog.showMessageDialog(parentForm, "Thông tin phụ huynh đã được lưu", "Thông báo");
            } else {
                MessageQLHSDialog.showMessageDialog(parentForm, "Thông tin phụ huynh được lưu do lỗi", "Cảnh báo");
            }
        }
        loadDataTable();
    }catch(Exception e) { 
        e.printStackTrace();
        MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaHS, sb, "Mã học sinh");
        DataValidator.validateEmpty(txtTen, sb, "Tên học sinh");
        if(sb.length()>0){ 
            MessageQLHSDialog.showErrorDialog(parentForm,sb.toString() ,"Lỗi" );
            return;
        }
        if(MessageQLHSDialog.showConfirmDialog(parentForm, "Bạn có muốn cập nhật lại thông tin học sinh không?","Hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try { 
             Phuhuynh ph = new Phuhuynh();
            ph.setMaHS(txtMaHS.getText());
            ph.setTencha(txtTencha.getText());
            ph.setSdtcha(txtSDTcha.getText());
            ph.setNncha(txtNNcha.getText());
            ph.setTenme(txtTenme.getText());
            ph.setSdtme(txtSDTme.getText());
            ph.setNnme(txtNNme.getText());
            
            PhuHuynhDao dao = new PhuHuynhDao();
           if(dao.update(ph)) { 
                MessageQLHSDialog.showMessageDialog(parentForm, "Học sinh đã được cập nhật", "Thông báo");
           }else{
               MessageQLHSDialog.showMessageDialog(parentForm, "Học Sinh không được cập nhật do lỗi", "Cảnh báo");
           }
           loadDataTable();
        }catch(Exception e) { 
            e.printStackTrace();
            MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         try{
            if (txtMaHS.getText().equals("")) {
                MessageQLHSDialog.showMessageDialog(parentForm, "Mã học sinh cần phải nhập", "Lỗi");
                return;
            }

            PhuHuynhDao dao = new PhuHuynhDao();
            Phuhuynh ph = dao.findmaHS(txtMaHS.getText());

            if(ph==null){
                MessageQLHSDialog.showMessageDialog(parentForm,"Không tìm thấy thông tin phụ huynh học sinh cần xóa" , "Lỗi");
                return;
            }
            if(MessageQLHSDialog.showConfirmDialog(parentForm, "Bạn có muốn xóa thông tin phụ huynh của học sinh không?", "Hỏi") == JOptionPane.NO_OPTION){
                return;
            }
            if(dao.delete(txtMaHS.getText())){
                MessageQLHSDialog.showMessageDialog(parentForm, "Thông tin phụ huynh của học sinh đã bị xóa" , "Thông báo");
            }else{
                MessageQLHSDialog.showMessageDialog(parentForm, "Thông tin phụ huynh của học sinh không bị xóa" , "Lỗi");
            }
            loadDataTable();
        }catch(Exception e){
            e.printStackTrace();
            MessageQLHSDialog.showMessageDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PHHSPanel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPHHS;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaHS;
    private javax.swing.JTextField txtNNcha;
    private javax.swing.JTextField txtNNme;
    private javax.swing.JTextField txtSDTcha;
    private javax.swing.JTextField txtSDTme;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTencha;
    private javax.swing.JTextField txtTenme;
    private javax.swing.JTextField txtmaHSsearch;
    // End of variables declaration//GEN-END:variables
}
