/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.BangDiemDao;
import dao.HocSinDao;
import helpers.DataValidator;
import helpers.MessageQLHSDialog;
import model.BangDiem;
import model.HocSinh;
import ui.MainForm;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QLDIEMHS extends javax.swing.JPanel {

    private MainForm parentForm;
    private DefaultTableModel tblModel;
    /**
     * Creates new form QLDIEMHS
     */
    
     public QLDIEMHS() {
        initComponents();
        
        initTable();
        
        loadDataTable();
    }
     
     private void initTable() {
        tblModel = new  DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Học Sinh","Toán","Văn","Anh","Lý","Hóa","Sinh","Sử","Địa","GDCD"});
        tblBangDiem.setModel(tblModel);
    }
    
    private void loadDataTable(){
        try{
            BangDiemDao dao = new BangDiemDao();
            List<BangDiem> list = dao.findAll();
            tblModel.setRowCount(0);
            for (BangDiem it : list){
                tblModel.addRow(new Object[]{
                        it.getMaHS(), it.getToan(), it.getVan(), it.getAnh(), it.getLy(), it.getHoa(), it.getSinh(),it.getSu(),it.getDia(),it.getGDCD()
                        });
            }tblModel.fireTableDataChanged();   
        }catch(Exception e){
            e.printStackTrace();
            MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaHS = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtToan = new javax.swing.JTextField();
        txtAnh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHoa = new javax.swing.JTextField();
        txtLy = new javax.swing.JTextField();
        txtSinh = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        txtSu = new javax.swing.JTextField();
        txtGDCD = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblDTB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLop = new javax.swing.JTextField();
        txtVan = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        txtmaHSsearch = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quản lý điểm học sinh");

        jLabel2.setText("Mã học sinh");

        jLabel3.setText("Mã học sinh");

        jLabel4.setText("Họ và tên ");

        jLabel5.setText("Toán");

        jLabel6.setText("Văn");

        jLabel7.setText("Anh");

        txtMaHS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaHSFocusLost(evt);
            }
        });
        txtMaHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHSActionPerformed(evt);
            }
        });

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        txtToan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToanActionPerformed(evt);
            }
        });

        txtAnh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnhActionPerformed(evt);
            }
        });

        jLabel10.setText("Lý");

        jLabel11.setText("Hóa");

        jLabel12.setText("Sinh");

        txtHoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoaActionPerformed(evt);
            }
        });

        txtLy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLyActionPerformed(evt);
            }
        });

        txtSinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSinhActionPerformed(evt);
            }
        });

        jLabel13.setText("Sử");

        jLabel14.setText("Địa");

        jLabel15.setText("GDCD");

        txtDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaActionPerformed(evt);
            }
        });

        txtSu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuActionPerformed(evt);
            }
        });

        txtGDCD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtGDCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGDCDActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Điểm trung bình");

        lblDTB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDTB.setText("0");
        lblDTB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblDTBFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDTB)
                        .addGap(45, 45, 45))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lblDTB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Lớp");

        txtLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLopActionPerformed(evt);
            }
        });

        txtVan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtToanFocusLost(evt);
            }
        });
        txtVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtToan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(txtGDCD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLop, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(txtTen)
                            .addComponent(txtMaHS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(txtLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(txtGDCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBangDiem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblBangDiemAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblBangDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangDiemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBangDiem);

        txtmaHSsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaHSsearchActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-16.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.setActionCommand("");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-icon-16.png"))); // NOI18N
        btnNew.setText("Tạo mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save-icon.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Close-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1)
                        .addContainerGap(399, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmaHSsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(btnSearch))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtmaHSsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnNew)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToanActionPerformed

    private void txtHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoaActionPerformed

    private void txtLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLyActionPerformed

    private void txtSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSinhActionPerformed

    private void txtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaActionPerformed

    private void txtSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuActionPerformed

    private void txtGDCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGDCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGDCDActionPerformed

    private void txtmaHSsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaHSsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaHSsearchActionPerformed

    private void txtAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnhActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLopActionPerformed

    private void txtMaHSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaHSFocusLost
        try {
            HocSinDao dao = new HocSinDao();
            HocSinh hs = dao.findmaHS(txtMaHS.getText());
            if (hs != null) {
                txtTen.setText(hs.getTenHS());
                txtLop.setText(hs.getLop());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtMaHSFocusLost

    private void txtToanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtToanFocusLost
        if (txtToan.getText().equals("")
                || txtVan.getText().equals("")
                || txtAnh.getText().equals("")
                || txtLy.getText().equals("")
                || txtHoa.getText().equals("")
                || txtSinh.getText().equals("")
                || txtSu.getText().equals("")
                || txtDia.getText().equals("")
                || txtGDCD.getText().equals("")) {
            return;
        }

        float Toan = Float.parseFloat(txtToan.getText());
        float Van = Float.parseFloat(txtVan.getText());
        float Anh = Float.parseFloat(txtAnh.getText());
        float Ly = Float.parseFloat(txtLy.getText());
        float Hoa = Float.parseFloat(txtHoa.getText());
        float Sinh = Float.parseFloat(txtSinh.getText());
        float Su = Float.parseFloat(txtSu.getText());
        float Dia = Float.parseFloat(txtDia.getText());
        float GDCD = Float.parseFloat(txtGDCD.getText());

        float avg = (Toan + Van + Anh + Ly + Hoa + Sinh + Su + Dia + GDCD) / 9;

        String st = String.format("%.2f", avg);
        lblDTB.setText(st);
    }//GEN-LAST:event_txtToanFocusLost

    private void lblDTBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblDTBFocusLost

    }//GEN-LAST:event_lblDTBFocusLost

    private void txtVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVanActionPerformed

    private void tblBangDiemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblBangDiemAncestorAdded

    }//GEN-LAST:event_tblBangDiemAncestorAdded

    private void tblBangDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangDiemMouseClicked
            try { 
            int row = tblBangDiem.getSelectedRow();
               
            if(row>=0){ 
                String id = (String) tblBangDiem.getValueAt(row, 0);
                BangDiemDao dao = new BangDiemDao();
                BangDiem bd = dao.findbyMaHS(id);
                HocSinDao dao1 = new HocSinDao();
                HocSinh hs = dao1.findmaHS(id);
                if(bd!=null){

                    txtMaHS.setText(bd.getMaHS());
                    txtTen.setText(hs.getTenHS());
                    txtLop.setText(hs.getLop());
                    txtToan.setText(String.format("%.2f", bd.getToan()));
                    txtVan.setText(String.format("%.2f", bd.getVan()));
                    txtAnh.setText(String.format("%.2f", bd.getAnh()));
                    txtLy.setText(String.format("%.2f", bd.getLy()));
                    txtHoa.setText(String.format("%.2f", bd.getHoa()));
                    txtSinh.setText(String.format("%.2f", bd.getSinh()));
                    txtSu.setText(String.format("%.2f", bd.getSu()));
                    txtDia.setText(String.format("%.2f", bd.getDia()));
                    txtGDCD.setText(String.format("%.2f", bd.getGDCD()));
                }
            }
        }catch(Exception e){ 
            e.printStackTrace();
            MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblBangDiemMouseClicked

    private void txtMaHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHSActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{ 
            BangDiemDao dao = new BangDiemDao();
            BangDiem bd = dao.findbyMaHS(txtmaHSsearch.getText());
            HocSinDao dao1 = new HocSinDao();
            HocSinh hs = dao1.findmaHS(txtmaHSsearch.getText());
            
            if(bd!=null){ 
                txtMaHS.setText(bd.getMaHS());
                txtTen.setText(hs.getTenHS());
                txtLop.setText(hs.getLop());
                txtToan.setText(String.format("%.2f", bd.getToan()));
                txtVan.setText(String.format("%.2f", bd.getVan()));
                txtAnh.setText(String.format("%.2f", bd.getAnh()));
                txtLy.setText(String.format("%.2f", bd.getLy()));
                txtHoa.setText(String.format("%.2f", bd.getHoa()));
                txtSinh.setText(String.format("%.2f", bd.getSinh()));
                txtSu.setText(String.format("%.2f", bd.getSu()));
                txtDia.setText(String.format("%.2f", bd.getDia()));
                txtGDCD.setText(String.format("%.2f", bd.getGDCD()));
                
                txtMaHSFocusLost(null);
                txtToanFocusLost(null);
            }else{
                MessageQLHSDialog.showMessageDialog(parentForm, "Không tìm thấy học sinh cần tìm", "Thông báo");
            }
        }catch(Exception e){ 
            e.printStackTrace();
            MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(),  "Lỗi");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtmaHSsearch.setText("");
        txtMaHS.setText("");
        txtTen.setText("");
        txtLop.setText("");
        txtToan.setText("");
        txtVan.setText("");
        txtAnh.setText("");
        txtLy.setText("");
        txtHoa.setText("");
        txtSinh.setText("");
        txtSu.setText("");
        txtDia.setText("");
        txtGDCD.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        StringBuilder sb = new StringBuilder();
    DataValidator.validateEmpty(txtMaHS, sb, "Mã học sinh cần nhập");
    if (sb.length() > 0) {
        MessageQLHSDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
        return;
    }
    try {
        BangDiem bd = new BangDiem();
        bd.setMaHS(txtMaHS.getText());
        bd.setToan(Float.parseFloat(txtToan.getText()));
        bd.setVan(Float.parseFloat(txtVan.getText()));
        bd.setAnh(Float.parseFloat(txtAnh.getText()));
        bd.setLy(Float.parseFloat(txtLy.getText()));
        bd.setHoa(Float.parseFloat(txtHoa.getText()));
        bd.setSinh(Float.parseFloat(txtSinh.getText()));
        bd.setSu(Float.parseFloat(txtSu.getText()));
        bd.setDia(Float.parseFloat(txtDia.getText()));
        bd.setGDCD(Float.parseFloat(txtGDCD.getText()));
        BangDiemDao dao = new BangDiemDao();

        if (dao.findbyMaHS(txtMaHS.getText()) != null) {
            if (MessageQLHSDialog.showConfirmDialog(parentForm, "Bạn có muốn lưu bảng điểm không", "Hỏi") == JOptionPane.YES_OPTION) {
                return;
            }
            if (dao.update(bd)) {
                MessageQLHSDialog.showMessageDialog(parentForm, "Bảng điểm đã được lưu", "Thông báo");
            } else {
                MessageQLHSDialog.showMessageDialog(parentForm, "Bảng điểm không được lưu do lỗi", "Cảnh báo");
            }
        } else {
            if (dao.insert(bd)) {
                MessageQLHSDialog.showMessageDialog(parentForm, "Bảng điểm đã được lưu", "Thông báo");
            } else {
                MessageQLHSDialog.showMessageDialog(parentForm, "Bảng điểm không được lưu do lỗi", "Cảnh báo");
            }
        }
        loadDataTable();
    } catch (Exception e) {
        e.printStackTrace();
        MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaHS, sb, "Mã học sinh");
        DataValidator.validateEmpty(txtTen, sb, "Tên học sinh");
        if(sb.length()>0){ 
            MessageQLHSDialog.showErrorDialog(parentForm,sb.toString() ,"Lỗi" );
            return;
        }
        if(MessageQLHSDialog.showConfirmDialog(parentForm, "Bạn có muốn cập nhật lại thông tin học sinh không?","Hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try { 
            BangDiem bd = new BangDiem();
            
            bd.setMaHS(txtMaHS.getText());
            bd.setToan(Float.parseFloat(txtToan.getText()));
            bd.setVan(Float.parseFloat(txtVan.getText()));
            bd.setAnh(Float.parseFloat(txtAnh.getText()));
            bd.setLy(Float.parseFloat(txtLy.getText()));
            bd.setHoa(Float.parseFloat(txtHoa.getText()));
            bd.setSinh(Float.parseFloat(txtSinh.getText()));
            bd.setSu(Float.parseFloat(txtSu.getText()));
            bd.setDia(Float.parseFloat(txtDia.getText()));
            bd.setGDCD(Float.parseFloat(txtGDCD.getText()));
            
            BangDiemDao dao = new BangDiemDao();
           if(dao.update(bd)) { 
                MessageQLHSDialog.showMessageDialog(parentForm, "Học sinh đã được cập nhật", "Thông báo");
           }else{
               MessageQLHSDialog.showMessageDialog(parentForm, "Học Sinh không được cập nhật do lỗi", "Cảnh báo");
           }
           loadDataTable();
        }catch(Exception e) { 
            e.printStackTrace();
            MessageQLHSDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            if (txtMaHS.getText().equals("")) {
                MessageQLHSDialog.showMessageDialog(parentForm, "Mã học sinh cần phải nhập", "Lỗi");
                 return;
            }
            
            BangDiemDao dao = new BangDiemDao();
            BangDiem bd = dao.findbyMaHS(txtMaHS.getText());
            
            if(bd==null){
                MessageQLHSDialog.showMessageDialog(parentForm,"Học sinh không có bản điểm điểm" , "Lỗi");
                return;
            }
            if(MessageQLHSDialog.showConfirmDialog(parentForm, "Bạn có muốn xóa điểm của học sinh không?", "Hỏi") == JOptionPane.NO_OPTION){
                return;
            }
            if(dao.deletebyMaHS(txtMaHS.getText())){
                MessageQLHSDialog.showMessageDialog(parentForm, "Điểm của học sinh đã bị xóa" , "Thông báo");
            }else{
                 MessageQLHSDialog.showMessageDialog(parentForm, "Điểm của học sinh không bị xóa" , "Lỗi");
            }
            loadDataTable();
                }catch(Exception e){
                    e.printStackTrace();
                    MessageQLHSDialog.showMessageDialog(parentForm, e.getMessage(), "Lỗi");
            }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblDTB;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTextField txtAnh;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtGDCD;
    private javax.swing.JTextField txtHoa;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtLy;
    private javax.swing.JTextField txtMaHS;
    private javax.swing.JTextField txtSinh;
    private javax.swing.JTextField txtSu;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtToan;
    private javax.swing.JTextField txtVan;
    private javax.swing.JTextField txtmaHSsearch;
    // End of variables declaration//GEN-END:variables
}
